In [2]:
import numpy as np
np. arange (10, 20, 4)

array([10, 14, 18])

In [6]:
numb = np.array ([26, 14, 5, 77, 399])
# numb[numb % 2 == 0]
numb[numb % 2 != 0]

array([  5,  77, 399])

In [3]:
numb = np.array ([26, 14, 5, 77, 399])
np.where(numb % 2 == 0, 'True', 'False')

array(['True', 'True', 'False', 'False', 'False'], dtype='<U5')

In [5]:
np.random.seed(20)
print(np.random.seed(20))

None


In [18]:
# a = np.array([9,8,7,6])
a = np.array([8,6,7,9])
b = np.array([1,2,3,4,5])
c = np.array([3,3,3])
print(np.argmax(a))
np.argmin(b)

3


0

In [14]:
np.argsort(a)

array([1, 2, 0, 3])

In [19]:
np.argsort(c)

array([0, 1, 2])

In [27]:
a = np.array([1,2,3,4])
print(np.quantile(a, 1))
print(np.quantile(a, 0))
print(np.quantile(a, 0.5))
# quantile value q to be between 0 and 1,

4
1
2.5
