### IN CLASS ASSIGNMENT
                      
DATE: 16/05/2025                          
TIME: 60 MIN

In [ ]:
print(f"Student ID: {input('Type your name: ')} {input('Type your surname: ')}")

In [11]:
import numpy as np
arr = np.array ([0,1,2,3,4,5,6,7,8,9])

print(arr.shape)
print(arr)
print(type(arr))

(10,)
[0 1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [15]:
# arr = np.arrange (10,20)
arr = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

# np.flip
print(arr[0:5])
print(arr[::2])
print(arr[::-1])

[10 11 12 13 14]
[10 12 14 16 18]
[19 18 17 16 15 14 13 12 11 10]


In [19]:
arr = np.array([1,2,3,4,5,6,7,8,9,10,11,12])

arr.reshape([3,4])
arr.reshape([2,6])

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [35]:
zeros_array = np.zeros((3, 3))
print(zeros_array)

ones_array = np.ones((2, 4))
print(ones_array)

identity_array = np.identity((4))
print(identity_array)

filled_array = np.full((5, 5), 7)
print(filled_array)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]
 [7 7 7 7 7]]


In [47]:
random_arr = np.arange(100)
# np.random.seed(100)
mean_arr = np.mean(random_arr)
std_arr = np.std(random_arr)
var_arr = np.var(random_arr)

print(random_arr)
print(mean_arr)
print(std_arr)
print(var_arr)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
49.5
28.86607004772212
833.25


In [51]:
arr = np.arange (1,20)
div_3 = arr[arr % 3 == 0]

print(arr)
print(div_3)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[ 3  6  9 12 15 18]


In [56]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

sum_arr = a + b
mult_arr = a * b
dot_prod_arr = np.dot(a, b)

print(sum_arr)
print(mult_arr)
print(dot_prod_arr)

[5 7 9]
[ 4 10 18]
32


In [58]:
matrix = np.ones((3, 3))
vector = np.array([1, 2, 3])

result = matrix + vector
print(result)

[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]


In [69]:
arr = np.random.randint(1, 101, size=10)
argsort_arr = np.argsort(arr)
sort_arr = np.sort(arr)
print(arr)
print(sort_arr)
print(argsort_arr)

[15 39 87 38  1 60 42 45 20 77]
[ 1 15 20 38 39 42 45 60 77 87]
[4 0 8 3 1 6 7 5 9 2]


In [66]:
arr = np.arange(10)
new_arr = np.where(arr < 5, -1, 1)

print(arr)
print(new_arr)

[0 1 2 3 4 5 6 7 8 9]
[-1 -1 -1 -1 -1  1  1  1  1  1]


In [67]:
arr = np.random.randn(100)
mean = np.mean(arr)
std = np.std(arr)
z_arr = (arr - mean) / std

print(z_arr)

[-2.45977692e+00  8.36386029e-01  4.87394462e-01 -1.11346879e-01
  2.49235360e-01  2.36050055e-01 -3.03890833e-01 -6.31365869e-01
  4.61694977e-01  4.29004486e-01  1.26791250e+00  1.44431656e+00
  8.67174246e-02 -1.35915533e+00 -3.52042817e-01 -6.17816278e-01
  1.55116760e-03 -1.76776690e+00  1.78963742e-01 -2.02359321e-01
  2.98006187e-01 -8.04129549e-01  5.88215915e-01  7.76065893e-01
  5.44701777e-02  1.11963939e+00  4.95715497e-01 -2.14374035e+00
 -1.06348572e-01 -1.78325962e-01  2.62287498e-01 -2.05322995e-01
 -1.88144180e+00 -3.02126946e-01 -1.39277031e-01 -1.55374549e+00
 -2.91464671e-01 -4.57754878e-01 -3.45747190e-01  5.77187722e-01
  2.41766357e+00 -1.39025381e+00 -4.66630686e-01 -1.07451027e+00
  7.79771670e-01 -4.93876422e-01 -1.12632901e+00 -9.49645060e-01
 -5.79115709e-01 -6.14252225e-02 -3.52714866e-01  1.04429851e+00
  1.24916714e+00  1.14566469e-01  1.30156984e-01 -7.28529928e-01
 -3.41589419e-01 -1.97202911e-01 -2.48639678e-01 -8.18422327e-01
  2.06384813e+00  6.45534

**1. Create and Inspect an Array**

Task:
- Create a 1D NumPy array of integers from 0 to 9.
- Print its shape, datatype, and number of dimensions.

**2. Array Indexing and Slicing**

Task:
- Given the array arr = np.arange(10, 20),
- Extract the first 5 elements
- Get every second element
- Reverse the array

**3. Reshape an Array**

Task:
- Create a 1D array with 12 elements. Reshape it into a 3×4 and then a 2×6 matrix.
- Print both reshaped arrays.

**4. Create Special Arrays**

Task:
Create the following arrays using NumPy:
- A 3×3 array of all zeros
- A 2×4 array of all ones
- A 4×4 identity matrix
- A 5×5 array filled with the number 7

**5. Random Array and Statistics**

Task:
- Generate a 1D array of 100 random numbers from a normal distribution.
- Compute and print the mean, standard deviation, and variance.

**6. Boolean Indexing**

Task:
- Create a NumPy array of numbers from 1 to 20.
- Extract all numbers divisible by 3.

**7. Element-wise Operations**

Task:
- Given a = np.array([1, 2, 3]) and b = np.array([4, 5, 6]), perform the following operations:

    1. Add a and b
    2. Multiply a and b element-wise
    3. Compute the dot product of a and b

**8. Broadcasting Practice**

Task:
- Create a 3×3 matrix of ones and a 1×3 vector [1, 2, 3].
- Add the vector to each row of the matrix using broadcasting.

**9. Sorting and Argsort**

Task:
- Create a random array of 10 integers between 1 and 100.
- Sort the array
- Print the indices that would sort the array (argsort)

**10. Conditional Selection with np.where()**

Task:
- Create an array of integers from 0 to 9.
- Use np.where() to replace values less than 5 with -1 and the rest with 1.

**11.  Z-score Standardization**

Task:
- Given an array of random values from a normal distribution, transform it into a standardized array using Z-score:
$(x - mean) / std$